set_property SRC_FILE_INFO {cfile:C:/Users/stuff/Documents/Projects/FPGA/MatrixDriver/MatrixDriver.srcs/constrs_1/imports/new/LEDMatrixConstraints.xdc rfile:../../../MatrixDriver.srcs/constrs_1/imports/new/LEDMatrixConstraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E18   IOSTANDARD LVCMOS33 } [get_ports { led0 }]; #IO_L16N_T2_A27_15 Sch=led[2]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H15   IOSTANDARD LVCMOS33 } [get_ports { led1 }]; #IO_L18P_T2_A24_15 Sch=led[5]
