set_property SRC_FILE_INFO {cfile:C:/Users/stuff/Documents/Projects/FPGA/LEDMatrix8x8/LEDMatrix8x8.srcs/constrs_1/new/LEDMatrixConstraints.xdc rfile:../../../LEDMatrix8x8.srcs/constrs_1/new/LEDMatrixConstraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U11   IOSTANDARD LVCMOS33 } [get_ports { rowPin[0] }]; #IO_L24P_T3_A01_D17_14        Sch=jd10/ck_io[26]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T11   IOSTANDARD LVCMOS33 } [get_ports { rowPin[1] }]; #IO_L23N_T3_A02_D18_14        Sch=jd9/ck_io[27]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R11   IOSTANDARD LVCMOS33 } [get_ports { rowPin[2] }]; #IO_L23P_T3_A03_D19_14        Sch=jd8/ck_io[28]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T13   IOSTANDARD LVCMOS33 } [get_ports { rowPin[3] }]; #IO_L22N_T3_A04_D20_14        Sch=jd7/ck_io[29]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T12   IOSTANDARD LVCMOS33 } [get_ports { rowPin[4] }]; #IO_L22P_T3_A05_D21_14        Sch=jd4/ck_io[30]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V13   IOSTANDARD LVCMOS33 } [get_ports { rowPin[5] }]; #IO_L21N_T3_DQS_A06_D22_14    Sch=jd3/ck_io[31]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U12   IOSTANDARD LVCMOS33 } [get_ports { rowPin[6] }]; #IO_L21P_T3_DQS_14            Sch=jd2/ck_io[32]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33 } [get_ports { rowPin[7] }]; #IO_L20N_T3_A07_D23_14        Sch=jd1/ck_io[33]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS33 } [get_ports { colPin[0] }]; #IO_L20P_T3_A08_D24_14        Sch=jc10/ck_io[34]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R13   IOSTANDARD LVCMOS33 } [get_ports { colPin[1] }]; #IO_L19N_T3_A09_D25_VREF_14   Sch=jc9/ck_io[35]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P13   IOSTANDARD LVCMOS33 } [get_ports { colPin[2] }]; #IO_L19P_T3_A10_D26_14        Sch=jc8/ck_io[36]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports { colPin[3] }]; #IO_L16P_T2_CSI_B_14          Sch=jc7/ck_io[37]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U18   IOSTANDARD LVCMOS33 } [get_ports { colPin[4] }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=jc4/ck_io[38]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U17   IOSTANDARD LVCMOS33 } [get_ports { colPin[5] }]; #IO_L15P_T2_DQS_RDWR_B_14     Sch=jc3/ck_io[39]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33 } [get_ports { colPin[6] }]; #IO_L18N_T2_A11_D27_14        Sch=jc2/ck_io[40]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U15   IOSTANDARD LVCMOS33 } [get_ports { colPin[7] }]; #IO_L18P_T2_A12_D28_14        Sch=jc1/ck_io[41]
